# Introduction To lists

In [1]:
# Lists, why would you need them?
# Congratulations! At this point in the course you are already familiar with:

# Vectors (one dimensional array): can hold numeric, character or logical values. 
# The elements in a vector all have the same data type.
# Matrices (two dimensional array): can hold numeric, character or logical values. 
# The elements in a matrix all have the same data type.
# Data frames (two-dimensional objects): can hold numeric, character or logical values. 
# Within a column all elements have the same data type, but different columns can be of different data type.
# Pretty sweet for an R newbie, right? ;-)

In [2]:
# Lists, why would you need them? (2)
# A list in R is similar to your to-do list at work or school: 
# the different items on that list most likely differ in length, characteristic, and type of activity that
# has to do be done.

# A list in R allows you to gather a variety of objects under one name 
# (that is, the name of the list) in an ordered way. These objects can be matrices, vectors, data frames,
# even other lists, etc. It is not even required that these objects are related to each other in any way.

# You could say that a list is some kind super data type: you can store practically any piece of information in it!

In [4]:
# Vector with numerics from 1 up to 10
my_vector <- 1:10 

# Matrix with numerics from 1 up to 9
my_matrix <- matrix(1:9, ncol = 3)

# First 10 elements of the built-in data frame mtcars
my_df <- mtcars[1:10,]

# Construct list with these different elements:
my_list <- list(my_vector, my_matrix, my_df)
my_list

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[3]]
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

# Naming A List

In [5]:
# Well done, you're on a roll!

# Just like on your to-do list, you want to avoid not knowing or remembering what the components of 
# your list stand for. That is why you should give names to them:

# my_list <- list(name1 = your_comp1, 
#                 name2 = your_comp2)
# This creates a list with components that are named name1, name2, and so on. 
# If you want to name your lists after you've created them, you can use the names() function as you did with vectors.
# The following commands are fully equivalent to the assignment above:

# my_list <- list(your_comp1, your_comp2)
# names(my_list) <- c("name1", "name2")

In [6]:
# Adapt list() call to give the components names
my_list <- list(vec = my_vector,mat = my_matrix, df = my_df)

# Print out my_list
my_list

$vec
 [1]  1  2  3  4  5  6  7  8  9 10

$mat
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$df
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

# Selecting a Items from the List

In [7]:
# Selecting elements from a list
# Your list will often be built out of numerous elements and components. 
# Therefore, getting a single element, multiple elements, or a component out of it is not always straightforward.

# One way to select a component is using the numbered position of that component. 
# For example, to "grab" the first component of shining_list you type

# shining_list[[1]]
# A quick way to check this out is typing it in the console. 
# Important to remember: to select elements from vectors, you use single square brackets: [ ]. Don't mix them up!

# You can also refer to the names of the components, with [[ ]] or with the $ sign. 
# Both will select the data frame representing the reviews:

# shining_list[["reviews"]]
# shining_list$reviews
# Besides selecting components, you often need to select specific elements out of these components. 
# For example, with shining_list[[2]][1] you select from the second component, actors (shining_list[[2]]), 
# the first element ([1]). When you type this in the console, you will see the answer is Jack Nicholson.

In [11]:
my_list[1]
my_list$df
my_list[2][]

$vec
 [1]  1  2  3  4  5  6  7  8  9 10

                  mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag     21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710        22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive    21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout 18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant           18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360        14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D         24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230          22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280          19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4

$mat
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

In [12]:
# Adding more movie information to the list
# Being proud of your first list, you shared it with the members of your movie hobby club.
# However, one of the senior members, a guy named M. McDowell, noted that you forgot to add the release year. 
# Given your ambitions to become next year's president of the club, you decide to add this information to the list.

# To conveniently add elements to lists you can use the c() function, that you also used to build vectors:

# ext_list <- c(my_list , my_val)
# This will simply extend the original list, my_list, with the component my_val. 
# This component gets appended to the end of the list. If you want to give the new list item a name,
# you just add the name as you did before:

# ext_list <- c(my_list, my_name = my_val)